apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdep
  namespace: fluxcdtutorial
  labels:
    name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginxpod
<<<<<<< HEAD
  replicas: 2
=======
  replicas: 6
>>>>>>> 79d8ac1 (replica 6)
  template:
    metadata:
      labels:
        app: nginxpod
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
