apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdep
  namespace: fluxcdtutorial
  labels:
    name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginxpod
  e plicas: 2
template:
    metadata:
      labels:
        app: nginxpod
    specinexistent:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80

